# sentinel/pipeline/models/base.py

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional
import numpy as np


@dataclass
class PredictionResult:
    """
    Returned by every model's predict() call.
    horizon_steps mirrors the number of steps ahead requested.
    """

    # predicted values, length = horizon_steps
    values: np.ndarray

    # timestamps corresponding to each predicted value
    timestamps: np.ndarray

    # optional lower and upper confidence bounds, same length as values
    lower_bound: Optional[np.ndarray] = None
    upper_bound: Optional[np.ndarray] = None

    # model version that produced this prediction
    model_version: Optional[str] = None


@dataclass
class TrainingResult:
    """
    Returned by every model's fit() and partial_fit() calls.
    Used by versioning and registry to record what happened.
    """

    # validation MAE on holdout set
    mae: float

    # validation MAPE on holdout set
    mape: float

    # number of samples trained on
    n_samples: int

    # whether this was a full retrain or finetune
    training_policy: str  # "full_retrain" or "finetune"

    # any model-specific metadata worth logging
    extra: dict = field(default_factory=dict)


class BaseModel(ABC):
    """
    Interface every Sentinel model must implement.

    Sentinel calls these methods in this order:
        1. fit()         — cold start, full retrain
        2. predict()     — called on every emitter tick
        3. partial_fit() — called on finetune trigger
        4. save()        — called after fit/partial_fit, before promotion
        5. load()        — called on startup if artifact exists

    Models must be stateless between calls except for internal
    learned parameters. All state that needs to persist across
    restarts must be serialized by save() and restored by load().
    """

    def __init__(self, granularity: str, horizon: str, lookback: str):
        """
        granularity : resolution of input data e.g. "1m"
        horizon     : how far ahead to predict e.g. "5m"
        lookback    : size of feature window e.g. "30m"

        Subclasses should call super().__init__() and then
        initialize their own internal parameters.
        """
        self.granularity = granularity
        self.horizon = horizon
        self.lookback = lookback
        self._is_fitted = False

    @abstractmethod
    def fit(self, X: np.ndarray, y: np.ndarray) -> TrainingResult:
        """
        Full retrain from scratch on the provided data.

        X : feature matrix, shape (n_samples, n_features)
            features are lag values auto-generated by features.py
        y : target values, shape (n_samples,)
            the actual metric values to predict

        Must set self._is_fitted = True on success.
        Must return a TrainingResult.
        """
        ...

    @abstractmethod
    def partial_fit(self, X: np.ndarray, y: np.ndarray) -> TrainingResult:
        """
        Finetune on recent data without discarding learned parameters.
        Called on low severity drift.

        Falls back to full fit() if model has not been fitted yet.
        Must return a TrainingResult with training_policy="finetune".
        """
        ...

    @abstractmethod
    def predict(self, X: np.ndarray) -> PredictionResult:
        """
        Generate multi-step ahead predictions.

        X : most recent feature window, shape (1, n_features)
            represents the latest observed state

        Returns PredictionResult with len(values) == horizon_steps.
        horizon_steps is derived from horizon / granularity internally.
        """
        ...

    @abstractmethod
    def save(self, path: str) -> None:
        """
        Serialize model state to the given path.
        Path is managed by versioning.py, model just writes to it.
        Format is up to the subclass — joblib, pickle, json etc.
        """
        ...

    @abstractmethod
    def load(self, path: str) -> None:
        """
        Restore model state from the given path.
        Must set self._is_fitted = True on success.
        """
        ...

    @property
    def is_fitted(self) -> bool:
        return self._is_fitted

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"granularity={self.granularity}, "
            f"horizon={self.horizon}, "
            f"lookback={self.lookback}, "
            f"fitted={self._is_fitted})"
        )